[phases.setup]
nixPkgs = ["nodejs", "nodejs.pkgs.npm"]

[phases.install]
cmds = ["npm install", "cd frontend && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "npm start"
